export const countries = [
    'South Korea',
    'Japan',
    'Thailand',
    'China',
    'Argentina',
    'Venezuela',
    'Mexico',
    'Brazil',
    'Germany',
    'Czech Republic',
    'Portugal',
    'Spain',
    'Italy',
    'Istambul',
    'Ethiopia',
    'Kenya',
    'Lebanon',
    'Iran',
    'United States',
    'Canada',
]